# Generated by Django 5.0.4 on 2024-06-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_student', models.BooleanField(default=None)),
                ('date_of_birth', models.DateTimeField()),
                ('national_id', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(upload_to='emogi')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from_home', models.TimeField()),
                ('distance_from_home', models.IntegerField()),
                ('college_name', models.CharField(max_length=1000)),
                ('section_name', models.CharField(max_length=10)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.student')),
            ],
        ),
    ]
