# Generated by Django 5.0.4 on 2024-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='distance_from_home',
            field=models.CharField(max_length=40),
        ),
    ]
