# Generated by Django 5.0.4 on 2024-06-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_classroom_distance_from_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='time_from_home',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_type', models.CharField(max_length=100)),
                ('breakfast_time', models.DateTimeField(default=True)),
                ('breakfast_duration', models.TimeField()),
                ('breakfast_place', models.CharField(max_length=70)),
                ('student_breakfast', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.student')),
            ],
        ),
    ]
