# Generated by Django 5.0.4 on 2024-06-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_classroom_time_from_home_breakfast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='breakfast_time',
            field=models.DateTimeField(),
        ),
    ]
