# Generated by Django 5.0.4 on 2024-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_breakfast_breakfast_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='breakfast_duration',
            field=models.CharField(max_length=50),
        ),
    ]
